version: '2'
services:
  zookeeper-1:
    image: zookeeper:3.8.0
    ports:
      - 12181:2181
      - 12182:2182
      - 8081:8080
    environment:
      - SERVER_ID=1
      - SERVER_COUNT=3
      - SERVER_NAME=zookeeper
      - ADMIN_USERNAME=zadmin
      - ADMIN_PASSWORD=zadmin
      - CLIENT_USERNAME=zclient
      - CLIENT_PASSWORD=zclient
      - QUORUM_AUTH_ENABLED=true
      - ENABLE_SSL=false
      - ENABLE_2WAY_SSL=false
      - ALLOW_NONENCRYPTED_ACCESS=true
  zookeeper-2:
    image: zookeeper:3.8.0
    ports:
      - 22181:2181
      - 22182:2182
      - 8082:8080
    environment:
      - SERVER_ID=2
      - SERVER_COUNT=3
      - SERVER_NAME=zookeeper
      - ADMIN_USERNAME=zadmin
      - ADMIN_PASSWORD=zadmin
      - CLIENT_USERNAME=zclient
      - CLIENT_PASSWORD=zclient
      - QUORUM_AUTH_ENABLED=true
      - ENABLE_SSL=false
      - ENABLE_2WAY_SSL=false
      - ALLOW_NONENCRYPTED_ACCESS=true
  zookeeper-3:
    image: zookeeper:3.8.0
    ports:
      - 32181:2181
      - 32182:2182
      - 8083:8080
    environment:
      - SERVER_ID=3
      - SERVER_COUNT=3
      - SERVER_NAME=zookeeper
      - ADMIN_USERNAME=zadmin
      - ADMIN_PASSWORD=zadmin
      - CLIENT_USERNAME=zclient
      - CLIENT_PASSWORD=zclient
      - QUORUM_AUTH_ENABLED=true
      - ENABLE_SSL=false
      - ENABLE_2WAY_SSL=false
      - ALLOW_NONENCRYPTED_ACCESS=true
  zookeeper-monitoring:
    image: zookeeper-monitoring:latest
    ports:
      - 8096:8096
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf
    environment:
      - ZOOKEEPER_HOST='zookeeper-1:2181','zookeeper-2:2181','zookeeper-3:2181'
      - PROMETHEUS_URLS='http://zookeeper-1:8080/metrics','http://zookeeper-2:8080/metrics','http://zookeeper-3:8080/metrics'
      - ZOOKEEPER_CLIENT_USERNAME=zclient
      - ZOOKEEPER_CLIENT_PASSWORD=zclient
      - OS_PROJECT=zookeeper-service
      - ZOOKEEPER_ENABLE_SSL=false
